# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

target 'Shaban' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Socket.IO-Client-Swift', '~>12.1.2' # Or latest version

  # Pods for Course App

end
